CUDA_VISIBLE_DEVICES="0" python main.py \
 --prompt 'high-resolution, ultra-sharp, detailed' \
 --image /root/autodl-tmp/data/train/low-light/high/10.png  \
 --neg_prompt '' \
 --images_path /root/autodl-tmp/data/test/super-resolution/low \
 --local_path /root/autodl-tmp/checkpoint/controlnet.bin \
 --use_controlnet \
 --model_type flux-dev \
 --width 1024 --height 1024  --timestep_to_start_cfg 5 \
 --num_steps 21 --true_gs 4 --guidance 4 \
 --control_weight 0.9 \
 --save_path results/sr
